version: '3.3'

services:
  postgres:
    container_name: shop_postgres
    image: postgres:12
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    
  bot:
    container_name: shop_bot
    env_file: .env
    build: .
    working_dir: /var/www/bot
    volumes:
      - .:/var/www/bot
    command: python main.py
    depends_on: 
      - postgres

  server:
    container_name: shop_server
    env_file: .env
    working_dir: /var/www/server
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server/:/var/www/server
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    expose:
      - ${SERVER_PORT}
    depends_on:
      - postgres
      - bot

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - server
